# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    #server-side
    - name: Install server dependencies
      run: |
        cd server
        npm ci
      
      working-directory: ./server

    - name: Build server (if needed)
      run: |
        cd server
        npm run build --if-present
      working-directory: ./server

    - name: Test server 
      run: |
        cd server
        npm test
      working-directory: ./server

    #client-side
    - name: Install client dependencies
      run: |
        cd client
        npm ci
      working-directory: ./client

    - name: Build client (if needed)
      run: |
        cd client
        npm run build --if-present
      working-directory: ./client

    - name: Test client
      run: |
        cd client
        npm test
      working-directory: ./client
